@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.ingeniarinoxidables.sghiiwebservice.modelo.Operario",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1197233471 { 
   	label=ingeniarinoxidables
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_593371288 { 
   	label=sghiiwebservice
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Herramienta1825860153[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Herramienta</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cantidad: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cantidad_disponible: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cantidad_kits: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   categoria: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   estado: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_in: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_out: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   items: List&lt;ItemHerramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   marca: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   proveedor: List&lt;Proveedor&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rol: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HerramientaResumenDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HerramientaResumenDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   herramientaEscasa: List&lt;Herramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramientasActivas: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramientasDeBaja: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramientasReg: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ingresosL30d: List&lt;Herramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   piezasActivas: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   piezasDisponibles: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   piezasKits: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   piezasPrestamo: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalPiezas: Long [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HerramientaResumenPorIdDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HerramientaResumenPorIdDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   itemsTool: List&lt;ItemHerramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listaUsoKits: List&lt;ListadoKitsTopDto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listaUsoOperarios: List&lt;ListadoOperariosTopDto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operDevoluciones: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operL30d: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operPrestamos: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   piezasDevueltas: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   piezasPrestadas: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalKits: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalOper: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalOperarios: Long [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ItemHerramienta1825860153[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ItemHerramienta</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   estado: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_in: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_out: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramienta: Herramienta [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   kits: List&lt;Kit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operaciones: List&lt;Operacion&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ItemHerramientaResumenPorIdDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ItemHerramientaResumenPorIdDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   devoluciones: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   itemKits: List&lt;Kit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   itemWorkers: List&lt;ListadoOperariosTopDto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prestamos: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalOper: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ubicacionKit: Kit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ubicacionWorker: Operario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Kit1825860153[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Kit</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   disponible: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   estado: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_in: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_out: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramientas: List&lt;ItemHerramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operaciones: List&lt;Operacion&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rol: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

KitResumenPorIdDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)KitResumenPorIdDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   listaUsoOperarios: List&lt;ListadoOperariosTopDto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operDevolucion: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operL30d: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operPrestamo: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalOperarios: Long [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListadoHerramientasTopDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListadoHerramientasTopDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cantidad: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tool: Herramienta [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListadoKitsTopDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListadoKitsTopDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cantidad: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   kit: Kit [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ListadoOperariosTopDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ListadoOperariosTopDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cantidad: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operario: Operario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Operacion1825860153[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Operacion</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fecha_operacion: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramienta: List&lt;ItemHerramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   kit: List&lt;Kit&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operario: Operario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tipo: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Operario1825860153[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Operario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   estado: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_in: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_out: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operaciones: List&lt;Operacion&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rol: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telefono: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OperarioResumenPorIdDto1350371111[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OperarioResumenPorIdDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   devoluciones: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listaUsoKits: List&lt;ListadoKitsTopDto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   listaUsoTools: List&lt;ListadoHerramientasTopDto&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operL30d: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   prestamos: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalKits: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalOper: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   totalTools: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Proveedor1825860153[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Proveedor</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ciudad: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   estado: Boolean [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_in: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fecha_out: LocalDate [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   herramientas: List&lt;Herramienta&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telefono: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Herramienta1825860153 -> ItemHerramienta1825860153[label="items
[0..*]"];
Herramienta1825860153 -> Proveedor1825860153[label="proveedor
[0..*]"];
HerramientaResumenDto1350371111 -> Herramienta1825860153[label="herramientaEscasa
[0..*]"];
HerramientaResumenDto1350371111 -> Herramienta1825860153[label="ingresosL30d
[0..*]"];
HerramientaResumenPorIdDto1350371111 -> ItemHerramienta1825860153[label="itemsTool
[0..*]"];
HerramientaResumenPorIdDto1350371111 -> ListadoKitsTopDto1350371111[label="listaUsoKits
[0..*]"];
HerramientaResumenPorIdDto1350371111 -> ListadoOperariosTopDto1350371111[label="listaUsoOperarios
[0..*]"];
ItemHerramienta1825860153 -> Herramienta1825860153[label="herramienta
[0..1]"];
ItemHerramienta1825860153 -> Kit1825860153[label="kits
[0..*]"];
ItemHerramienta1825860153 -> Operacion1825860153[label="operaciones
[0..*]"];
ItemHerramientaResumenPorIdDto1350371111 -> Kit1825860153[label="itemKits
[0..*]"];
ItemHerramientaResumenPorIdDto1350371111 -> Kit1825860153[label="ubicacionKit
[0..1]"];
ItemHerramientaResumenPorIdDto1350371111 -> ListadoOperariosTopDto1350371111[label="itemWorkers
[0..*]"];
ItemHerramientaResumenPorIdDto1350371111 -> Operario1825860153[label="ubicacionWorker
[0..1]"];
Kit1825860153 -> ItemHerramienta1825860153[label="herramientas
[0..*]"];
Kit1825860153 -> Operacion1825860153[label="operaciones
[0..*]"];
KitResumenPorIdDto1350371111 -> ListadoOperariosTopDto1350371111[label="listaUsoOperarios
[0..*]"];
ListadoHerramientasTopDto1350371111 -> Herramienta1825860153[label="tool
[0..1]"];
ListadoKitsTopDto1350371111 -> Kit1825860153[label="kit
[0..1]"];
ListadoOperariosTopDto1350371111 -> Operario1825860153[label="operario
[0..1]"];
Operacion1825860153 -> ItemHerramienta1825860153[label="herramienta
[0..*]"];
Operacion1825860153 -> Kit1825860153[label="kit
[0..*]"];
Operacion1825860153 -> Operario1825860153[label="operario
[0..1]"];
Operario1825860153 -> Operacion1825860153[label="operaciones
[0..*]"];
OperarioResumenPorIdDto1350371111 -> ListadoHerramientasTopDto1350371111[label="listaUsoTools
[0..*]"];
OperarioResumenPorIdDto1350371111 -> ListadoKitsTopDto1350371111[label="listaUsoKits
[0..*]"];
Proveedor1825860153 -> Herramienta1825860153[label="herramientas
[0..*]"];
    
}
@enduml