@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.ingeniarinoxidables.sghiiwebservice.controlador.HerramientaControlador",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1197233471 { 
   	label=ingeniarinoxidables
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_593371288 { 
   	label=sghiiwebservice
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   HerramientaControlador236320816[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HerramientaControlador</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   itemHerramientaServicio: ItemHerramientaServicio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   service: HerramientaServicio [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ actualizar(id: String, herramienta: Herramienta): ResponseEntity&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ agregar(herramienta: Herramienta): ResponseEntity&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ eliminar(id: String): ResponseEntity&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listar(): ResponseEntity&lt;List&lt;Herramienta&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarOperaciones(id: String): ResponseEntity&lt;List&lt;Operacion&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarProveedores(id: String): ResponseEntity&lt;List&lt;Proveedor&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ obtenerPorId(id: String): ResponseEntity&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumen(): ResponseEntity&lt;HerramientaResumenDto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumenPorId(id: String): ResponseEntity&lt;HerramientaResumenPorIdDto&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

HerramientaServicio8218601[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HerramientaServicio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   kitRepositorio: KitRepositorio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operacionRepositorio: OperacionRepositorio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operarioRepositorio: OperarioRepositorio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repositorio: HerramientaRepositorio [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addProveedor(idHerramienta: String, proveedor: Proveedor): Herramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ dropSuplier(idHerramienta: String, Suplier: Proveedor): Herramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ eliminarHerramienta(id: String): Herramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ guardarHerramienta(herramienta: Herramienta): Herramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarHerramientas(): List&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarHerramientasPorEstado(estado: Boolean): List&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarOperacionesTool(id: String): List&lt;Operacion&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarProveedores(id: String): List&lt;Proveedor&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ obtenerHerramientaPorId(id: String): Optional&lt;Herramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumen(): HerramientaResumenDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumenPorId(id: String): HerramientaResumenPorIdDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ItemHerramientaServicio8218601[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ItemHerramientaServicio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   herramientaRepositorio: HerramientaRepositorio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   operarioServicio: OperarioServicio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repositorio: ItemHerramientaRepositorio [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ eliminarItemHerramienta(id: int): ItemHerramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ guardarItem(item: ItemHerramienta): ItemHerramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ itemParaAsignar(items: List&lt;ItemHerramienta&gt;): ItemHerramienta</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarItemsByTool(idTool: String): List&lt;ItemHerramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarItemsHerramientas(): List&lt;ItemHerramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarItemsHerramientasByEstado(estado: Integer): List&lt;ItemHerramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarOperacionesItem(id: int): List&lt;Operacion&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ obtenerItemHerramienta(id: int): Optional&lt;ItemHerramienta&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumenPorId(id: int): ItemHerramientaResumenPorIdDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OperarioServicio8218601[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OperarioServicio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   repositorio: OperarioRepositorio [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repositorioKits: KitRepositorio [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ eliminarOperario(id: String): Operario</TD></TR>
<TR><TD ALIGN="LEFT" >- frecuenciaListaKits(listado: List&lt;Kit&gt;): HashMap&lt;String, Integer&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- frecuenciaListaTools(listado: List&lt;Operacion&gt;): HashMap&lt;Integer, Long&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ guardarOperario(operario: Operario): Operario</TD></TR>
<TR><TD ALIGN="LEFT" >+ herramientasPrestamoActivo(idOperario: String): ListaContenedor&lt;ItemHerramienta, Kit&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarOperarios(): List&lt;Operario&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listarOperariosPorEstado(estado: Boolean): List&lt;Operario&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ obtenerOperarioPorId(id: String): Operario</TD></TR>
<TR><TD ALIGN="LEFT" >+ operacionesWorker(id: String): List&lt;Operacion&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumen(): OperarioResumenDto</TD></TR>
<TR><TD ALIGN="LEFT" >+ resumenPorID(id: String): OperarioResumenPorIdDto</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
HerramientaControlador236320816 -> HerramientaServicio8218601[label="service
[1]"];
HerramientaControlador236320816 -> ItemHerramientaServicio8218601[label="itemHerramientaServicio
[1]"];
ItemHerramientaServicio8218601 -> OperarioServicio8218601[label="operarioServicio
[1]"];
    
}
@enduml